CELEBA_IMAGE_SIZE = 84
CELEBA_CLASSES = 2

FEMNIST_IMAGE_SIZE = 28
FEMNIST_CLASSES = 62

LEAF_CHARACTERS = (
    "\n !\"&'(),-.0123456789:;>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]abcdefghijklmnopqrstuvwxyz}"
)
