CELEBA_IMAGE_SIZE = 84
CELEBA_CLASSES = 2

FEMNIST_IMAGE_SIZE = 28
FEMNIST_CLASSES = 62

CIFAR_10_CLASSES = 10
CIFAR_10_IMAGE_SIZE = 32
CIFAR_10_IMAGE_DIMENSIONS = 3

LEAF_CHARACTERS = "\n !\"&'(),-.0123456789:;>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]abcdefghijklmnopqrstuvwxyz}"

DATASET_NAME_LIST = ["femnist", "celeba", "shakespeare"]
